# Generated by Django 3.2.9 on 2022-01-22 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255, verbose_name='Название устройства')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('specifications', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Дополнительное фото(2)')),
                ('photo3', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Дополнительное фото(3)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('price', models.IntegerField(default=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='isSaled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_carts', models.IntegerField(default=True)),
                ('Good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.good')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='carts',
            field=models.ManyToManyField(related_name='goods', through='good.isSaled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='good',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='good.category', verbose_name='Категории'),
        ),
    ]
