# Generated by Django 3.2.9 on 2022-01-22 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('specifications', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Дополнительное фото(2)')),
                ('photo3', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Дополнительное фото(3)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('price', models.IntegerField(default=True, verbose_name='Цена')),
            ],
        ),
        migrations.RemoveField(
            model_name='issaled',
            name='Good',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.AddField(
            model_name='goods',
            name='carts',
            field=models.ManyToManyField(related_name='goods', through='good.isSaled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goods',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='good.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='issaled',
            name='Goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='good.goods'),
            preserve_default=False,
        ),
    ]
