# Generated by Django 3.2.9 on 2021-12-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='good.category', verbose_name='Категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='cat_name',
            field=models.CharField(max_length=255, verbose_name='Название устройства'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='good',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='good',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='good',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='good',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='good',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
