# Generated by Django 3.2.9 on 2021-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20211204_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.IntegerField(default=True, verbose_name='Цена'),
        ),
    ]
