# Generated by Django 3.2.9 on 2022-01-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_good_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='photo2',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/', verbose_name='Дополнительное фото(2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='photo3',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/', verbose_name='Дополнительное фото(3)'),
            preserve_default=False,
        ),
    ]
