# Generated by Django 3.2.9 on 2022-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_rename_issaled_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='count_goods',
            field=models.IntegerField(default=True),
        ),
    ]
